//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaMasters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaMastersEntities : DbContext
    {
        public CinemaMastersEntities()
            : base("name=CinemaMastersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<FilmHasKinosaal> FilmHasKinosaal { get; set; }
        public virtual DbSet<Kinobesucher> Kinobesucher { get; set; }
        public virtual DbSet<Kinosaal> Kinosaal { get; set; }
        public virtual DbSet<Platz> Platz { get; set; }
        public virtual DbSet<Reihe> Reihe { get; set; }
        public virtual DbSet<Reservierung> Reservierung { get; set; }
        public virtual DbSet<ReservierungHasPlatz> ReservierungHasPlatz { get; set; }
        public virtual DbSet<Vorstellung> Vorstellung { get; set; }
    }
}
