//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaMasters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservierungHasPlatz
    {
        public int Id { get; set; }
        public int ReservierungId { get; set; }
        public int PlatzId { get; set; }
    
        public virtual Platz Platz { get; set; }
        public virtual Reservierung Reservierung { get; set; }
    }
}
